# Configuration
# --------------------------------------

source $HOME/.zsh/variables.zsh

plugins=(git zsh-autosuggestions zsh-syntax-highlighting zsh-history-substring-search)
source $ZSH/oh-my-zsh.sh
